### ISSUE TITLE
Traversing a TOML structure that is not known a priori

### ISSUE THREAD

**Issue by seekM** [asafh/jtoml#8]
Is it possible to traverse a TOML structure that is not known a priori?

E.g. I have a file whose structure looks likes this:

```
["unknown-string-1"]
channel_id = "foo"
keywords = ["foo, foo"]

["unknown-string-2"]
channel_id = "bar"
keywords = ["bar, bar"]
```

I don't know the table names. Is it possible to iterate over the tables and access their names?

**Comment by asafh** [comment]
Hi @seekM,
Yes it is, the parse* methods return a io.ous.jtoml.Toml instance which is a subclass of a Map<String, Object> - you can use 
```java
Toml toml = JToml.parse(new File("/example.toml")); //Your example
for (String key : toml.keySet()) {
    try {
        TomlTable myTable = toml.getTomlTable(key);
    } catch (ClassCastException e) {
        //you had something other than tables in this level, you can use getValue and checking using instanceof TomlTable to avoid the exception
    }
}
```
